### ISSUE TITLE
Added a couple of more plots 

### ISSUE THREAD

**Issue by davidjayjackson** [jacquietran/wnblr#33]
https://github.com/davidjayjackson/streamRs-jacquietran

David

**Comment by jacquietran** [comment]
thanks for sharing @davidjayjackson! if sharing examples of your work using {wnblr}, i suggest posting in my channel on the streameR discord server instead of here.

i'd like to use this space specifically for logging issues that users encounter with the package, so that i have a clear and accurate record of what needs fixing. thank you!
